2023-01-23 11:54:43,941 ERROR: Exception on /user/Pepe [GET] [in C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Program Files\Coding Stuff\Flask\app\routes.py", line 76, in user
    return render_template('user.html', user=user, posts=posts)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Program Files\Coding Stuff\Flask\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Program Files\Coding Stuff\Flask\app\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Program Files\Coding Stuff\Flask\app\templates\user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-01-23 11:56:27,995 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-23 12:10:09,118 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-23 12:22:17,936 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-23 12:38:05,962 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-23 12:50:29,096 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-23 13:01:10,646 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-23 13:07:29,262 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-23 13:10:36,640 INFO: Microblog Start-up [in c:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-23 13:10:44,336 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-23 22:46:14,496 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-26 11:55:34,195 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:45]
2023-01-26 12:01:31,212 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:45]
2023-01-26 12:09:32,121 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:45]
2023-01-26 12:26:11,346 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:48]
2023-01-26 12:27:51,080 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:48]
2023-01-26 13:23:41,443 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:48]
2023-01-26 13:31:54,951 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:48]
2023-01-26 13:34:20,023 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:48]
2023-01-26 13:38:54,317 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:48]
2023-01-26 13:39:22,011 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:48]
2023-01-30 13:42:52,328 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:48]
2023-01-30 14:43:57,605 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:48]
2023-01-30 14:44:32,385 ERROR: Exception on /reset_password_request [GET] [in C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\Coding Stuff\Flask\app\routes.py", line 174, in reset_password_request
    if form.validate_on_submit():
TypeError: FlaskForm.validate_on_submit() missing 1 required positional argument: 'self'
2023-01-30 14:44:41,191 ERROR: Exception on /reset_password_request [GET] [in C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\Coding Stuff\Flask\app\routes.py", line 174, in reset_password_request
    if form.validate_on_submit():
TypeError: FlaskForm.validate_on_submit() missing 1 required positional argument: 'self'
2023-01-30 14:44:51,155 ERROR: Exception on /reset_password_request [GET] [in C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\Coding Stuff\Flask\app\routes.py", line 174, in reset_password_request
    if form.validate_on_submit():
TypeError: FlaskForm.validate_on_submit() missing 1 required positional argument: 'self'
2023-01-30 14:46:50,490 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:48]
2023-01-30 14:46:57,979 ERROR: Exception on /reset_password_request [GET] [in C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\Coding Stuff\Flask\app\routes.py", line 174, in reset_password_request
    if form.validate_on_submit():
TypeError: FlaskForm.validate_on_submit() missing 1 required positional argument: 'self'
