2023-01-30 14:58:05,839 ERROR: Exception on /reset_password_request [POST] [in C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 872, in sendmail
    self.ehlo_or_helo_if_needed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 611, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 451, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\Coding Stuff\Flask\app\routes.py", line 177, in reset_password_request
    send_password_reset_email(user)
  File "C:\Program Files\Coding Stuff\Flask\app\email.py", line 15, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Program Files\Coding Stuff\Flask\app\email.py", line 10, in send_email
    msg.html = html_body
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 1004, in quit
    res = self.docmd("quit")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2023-01-30 15:23:38,165 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:48]
