2023-01-20 11:14:41,476 ERROR: Exception on /user/Sano [GET] [in C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Program Files\Coding Stuff\Flask\app\routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Program Files\Coding Stuff\Flask\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Program Files\Coding Stuff\Flask\app\templates\base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Program Files\Coding Stuff\Flask\app\templates\user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-01-20 11:14:44,170 ERROR: Exception on /user/Sano [GET] [in C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Program Files\Coding Stuff\Flask\app\routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Program Files\Coding Stuff\Flask\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Program Files\Coding Stuff\Flask\app\templates\base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Program Files\Coding Stuff\Flask\app\templates\user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-01-20 11:18:03,783 ERROR: Exception on /user/Susan [GET] [in C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Program Files\Coding Stuff\Flask\app\routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Program Files\Coding Stuff\Flask\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Program Files\Coding Stuff\Flask\app\templates\base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Program Files\Coding Stuff\Flask\app\templates\user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-01-20 12:06:41,073 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-20 12:07:15,984 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-20 12:09:01,465 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-20 12:09:52,786 INFO: Microblog Start-up [in C:\Program Files\Coding Stuff\Flask\app\__init__.py:42]
2023-01-20 12:09:56,847 ERROR: Exception on /index [GET] [in C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Program Files\Coding Stuff\Flask\app\routes.py", line 31, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Program Files\Coding Stuff\Flask\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Program Files\Coding Stuff\Flask\app\templates\index.html", line 16, in template
    {{% for post in posts %}}
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
